spring:
  application:
    name: flight-booking-app

  datasource:
    url: jdbc:postgresql://localhost:5432/flight_booking
    username: postgres
    password:
    driver-class-name: org.postgresql.Driver

  sql:
    init:
      mode: always

  jpa:
    hibernate:
      ddl-auto: update
    show-sql: true
    properties:
      hibernate:
        format_sql: true

server:
  port: 8080
