version: '3.8'
services:
  db:
    image: postgres:15
    container_name: flight_booking_db
    restart: always
    environment:
      POSTGRES_DB: flight_booking
      POSTGRES_USER: root
      POSTGRES_PASSWORD: 123456
    ports:
      - "5432:5432"
    volumes:
      - postgres_data:/var/lib/postgresql/data

volumes:
  postgres_data: